CA=float(input("Chelines austriacos: "))
print("Son equivalentes a ", round(CA*9568.71,2), "pesetas")
DG=float(input("Dracmas griegos: "))
print("Son equivalentes a ", round(DG*0.04406,2), "francos franceses")
PS=float(input("Pesetas: "))
print("Son equivalentes a ", round(PS/122499,5), "Dólares")
print("Son equivalentes a ", round(DG*0.010765,2), "Liras italianas")